#!/bin/sh

fail () {
  echo "\033[31m  ✘ $1\033[0m"
  exit 1
}

success () {
  echo "\033[32m  ✔ $1\033[0m"
}

spec () {
  [ $? -eq 0 ] || fail "$1"
  success "$1"
}

describe () {
  echo "\033[1m$1\033[0m"
}
