#!/bin/sh

. test/helpers

describe "give/init"

export give_dir="/tmp/give-$RANDOM"

./give.sh init

[ -d "$give_dir/src/node/.git" ]
spec "give should clone node.js repository to it's home directory"

[ -d "$give_dir/src/iojs/.git" ]
spec "give should clone io.js repository to it's home directory"

rm -rf "$give_dir"
