#!/bin/sh

. test/helpers

describe "give/rm"

export give_dir="/tmp/give-$RANDOM"

mkdir -p $give_dir/{installed,src}/node-master
touch $give_dir/{installed,src}/node-master/file

./give.sh rm node master

[ ! -d "$give_dir/src/node-master" ]
spec "give should delete source directory"

[ ! -d "$give_dir/installed/node-master" ]
spec "give should delete install directory"

rm -rf "$give_dir"
